<a href="https://colab.research.google.com/github/MinghanChu/DeepLearning-ZerosToGans/blob/main/Pytorch%20tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import `pytorch`

In [2]:
import torch

# Outline
+ Pytorch **tensors**
+ Tensor operations and **gradients**
+ Interoperability between **PyTorch** and **Numpy**

In [3]:
#Number
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is a shorthand for `4.0`. It is used to indicate to Python that you want to create a floating-point number. Check the type using `dtype`.

we want to use floating point tensors for deep-learning because

+ deep learning always doesn't produce integer results

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

All the elements of a tensor have the same type. In this case, floating point.

In [6]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

Two dimentional matrix: 3 rows and 2 columns.

###Three dimensional array:
whenever you have more than one matrix in an array you are having a three dimensional matrix.

+ more than one matrix, plus rows and columns in each matrix
+ `t4_1.shape`: `([2,2,3])`: first `2` means `2` matrices; second `2` means `2` rows, and third `3` means `3` columns

In [7]:
# 3-dimentional array
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
     [[15,16,17],
      [17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [8]:
# newly added array
t4_1 = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6]],
    [[5,6,7],
     [8,9,10]]
])
t4_1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 5,  6,  7],
         [ 8,  9, 10]]])

In [9]:
t4_1.shape

torch.Size([2, 2, 3])

Two matrices that have the same number of rows and columns.

In [10]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

check tensor's dimension using `shape`. empty `[]` means zero dimension.

In [11]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

size of 4 means the tensor has four elements.

In [12]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

From outside in, you are having `3` rows, and `2` columns. Then the size of `t3` is `[3,2]`.

In [13]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

From outside in, you are having `2` matrices, `2` rows, and `3` columns. Then the size of the tensor is `[2,2,3]`.

You cannot have an inappropriate tensor shape. See the following example:

In [14]:
t5 = torch.tensor([[5., 6, 11],
                   [7,8],
                   [9,10]]
)
t5

ValueError: expected sequence of length 3 at dim 1 (got 2)

You see from the above example that you have `3` columns in the first row, but only `2` colmns in the second and the third row. They must match to avoid errors.

Tensor can be integrated with **arithmatic operations**. In the following example, `y` is created using an arithmatic expression that combines three tensors.

In [15]:
#Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

print(x)

tensor(3.)


Note that `requires_grad=True` condition is used for `w` and `b`, but not used for `x`. This means we are only interested in calculating the derivative or gradient wrt `w` and `b`.

In [17]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` has a size of `17`, because size of `x` * size of `w` + size of `b` = `3 * 4 + 5 = 17`.

If we want to take derivative of `y` wrt either, `w` , `x` or `b`, use `y.backward()`:

In [18]:
y.backward()

The derivatives of `y` wrt these three tensors (`w`, `x`, `b`) can be accessed through `grad`.

In [19]:
#Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Let's take a closer look at the outputted results. `dy/dx` outputs `None` for the gradient because we wasn't interested in its gradient. `dy/dw = x` (`b` is a constant here), `x` has the size of `3`. `dy/db = 1`.

Let's see other torch method examples:

In [20]:
t6 = torch.full((3,2), 44)
t6

tensor([[44, 44],
        [44, 44],
        [44, 44]])

In [21]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [44., 44.],
        [44., 44.],
        [44., 44.]])

`Cat()` in PyTorch is used for concatenating two or more tensors in the same dimension.

In [22]:
print(t7)
t7.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [44., 44.],
        [44., 44.],
        [44., 44.]])


torch.Size([6, 2])

In [23]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [ 0.0177,  0.0177],
        [ 0.0177,  0.0177],
        [ 0.0177,  0.0177]])

`torch.sin()` evaluates `sin` of each entry element.

In [24]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [ 0.0177,  0.0177]],

        [[ 0.0177,  0.0177],
         [ 0.0177,  0.0177]]])

Check [Tensor operations](https://pytorch.org/docs/stable/torch.html)

`numpy` is an open-source library for mathematical and scientific computing in Python to deal with multi-dimensional large arrays. It has a vast ecosystem of supporting libraries, including

+ Pandas (I/O and data analysis)
+ Matplotlib (plotting and visualization)
+ OpenCV (image and video processing)

Always use **floating** by setting one of these elements be a float, e.g. `4.` with a dot after.

In [25]:
# note that
import numpy as np

x = np.array(
    [[1,2],
    [2,4.]]
)
x

array([[1., 2.],
       [2., 4.]])

In [26]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [2., 4.]], dtype=torch.float64)

In [27]:
# check the data type for Numpy (Python) and torch
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In conclution, the types are very similar but not exactly the same. Why do we even need `PyTorch` then if **`Numpy()`** can do very well with multi-dimentional operations?

The reason is `Numpy()` is a very powerful python library to process complex arrays. But `PyTorch` automatically computes

+ gradients using `Autograd` which is essential for **deep learning.**
+ and very effeciently works with **massive datasets** on `GPU`. For example, it only takes minutes than hours if GPU is used.

Therefore, we benefit from `Numpy()` for processing complex multi-dimentional matrices and convert the result to the data type that is compaitible with `PyTorch` to do **deep learning**. **To convert Numpy data type to Pytorch data type just do the following:**

In [28]:
# Note that y is originally a pytorch data type and y.numpy() will convert it to numpy data type

z = y.numpy()
print(z)

[[1. 2.]
 [2. 4.]]


Given `numpy` already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. GPU support: while working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit(GPU). Computations that might take hours can be completed within minutes using GPUs.