<a href="https://colab.research.google.com/github/Renshui-MC/DeepLearning-ZerosToGans/blob/main/Pytorch%20tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#Number
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is a shorthand for `4.0`. It is used to indicate to Python that you want to create a floating-point number. Check the type using `dtype`.

In [ ]:
t1.dtype

torch.float32

In [ ]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

All the elements of a tensor have the same type. In this case, floating point. 

In [ ]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

Two dimentional matrix: 3 rows and 2 columns. 

In [ ]:
# 3-dimentional array
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
     [[15,16,17],
      [17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Two matrices that have the same number of rows and columns. 

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

check tensor's dimension using `shape`. empty `[]` means zero dimension. 

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

size of 4 means the tensor has four elements.

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

From outside in, you are having `3` rows, and `2` columns. Then the size of `t3` is `[3,2]`.

In [ ]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

From outside in, you are having `2` matrices, `2` rows, and `3` columns. Then the size of the tensor is `[2,2,3]`. 

You cannot have an inappropriate tensor shape. See the following example:

In [ ]:
t5 = torch.tensor([[5., 6, 11],
                   [7,8],
                   [9,10]]
)
t5

ValueError: ignored

You see from the above example that you have `3` columns in the first row, but only `2` colmns in the second and the third row. They must match to avoid errors.

Tensor can be integrated with **arithmatic operations**. In the following example, `y` is created using an arithmatic expression that combines three tensors. 

In [ ]:
#Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

Note that `requires_grad=True` condition is used for `w` and `b`, but not used for `x`. This means we are only interested in calculating the derivative or gradient wrt `w` and `b`.

In [ ]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` has a size of `17`, because size of `x` * size of `w` + size of `b` = `3 * 4 + 5 = 17`.

If we want to take derivative of `y` wrt either, `w` , `x` or `b`, use `y.backward()`:

In [ ]:
y.backward()

The derivatives of `y` wrt these three tensors (`w`, `x`, `b`) can be accessed through `grad`. 

In [ ]:
#Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Let's take a closer look at the outputted results. `dy/dx` outputs `None` for the gradient because we wasn't interested in its gradient. `dy/dw = x` (`b` is a constant here), `x` has the size of `3`. `dy/db = 1`.

Let's see other torch method examples:

In [ ]:
t6 = torch.full((3,2), 44)
t6

tensor([[44, 44],
        [44, 44],
        [44, 44]])

In [ ]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [44., 44.],
        [44., 44.],
        [44., 44.]])

`Cat()` in PyTorch is used for concatenating two or more tensors in the same dimension.

In [ ]:
print(t7)
t7.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [44., 44.],
        [44., 44.],
        [44., 44.]])


torch.Size([6, 2])

In [ ]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [ 0.0177,  0.0177],
        [ 0.0177,  0.0177],
        [ 0.0177,  0.0177]])

`torch.sin()` evaluates `sin` of each entry element.

In [ ]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [ 0.0177,  0.0177]],

        [[ 0.0177,  0.0177],
         [ 0.0177,  0.0177]]])

Check [Tensor operations](https://pytorch.org/docs/stable/torch.html)

Test the new commit